import { Ritual, LoreNode } from './types';

export const rituals: Ritual[] = [
  {
    id: 'ritual-016',
    title: 'Yüksek Yüksek Tepelere',
    slug: 'yuksek-yuksek-tepelere',
    releaseDate: '2025-07-10',
    description: 'A traditional mourning anthem, deconstructed into a digital lament. Echoes from the peaks of the Anatolian Void.',
    coverImage: 'https://imagine-public.x.ai/imagine-public/images/4e2b1a98-b4c6-4284-9800-3a6d64e42ee1.jpg?cache=1',
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Yuksek%20yuksek%20Tepelere.mp3',
    emotionalPhase: 'ANATOLIAN_DECAY',
    ritualText: [
      '[Verse 1]',
      'Yüksek yüksek tepelere ev kurmasınlar',
      'Aşrı aşrı memlekete kız vermesinler',
      'Annesinin bir tanesini hor görmesinler',
      '',
      '[Chorus]',
      'Uçan da kuşlara malum olsun',
      'Ben annemi özledim',
      'Hem babamı özledim',
      'Hem köyümü özledim',
      '',
      '[Verse 2]',
      'Babamın bir atı olsa binse de gelse',
      'Annemin yelkeni olsa açsa da gelse',
      'Kardeşlerim yollarımı bilse de gelse',
      '',
      '[Chorus]',
      'Uçan da kuşlara malum olsun',
      'Ben annemi özledim',
      'Hem babamı özledim',
      'Hem köyümü özledim'
    ],
    syncedLyrics: [
      { time: 0, text: "[Intro: Vocal Drones]" },
      { time: 5, text: "Yüksek yüksek tepelere" },
      { time: 8, text: "ev kurmasınlar" },
      { time: 12, text: "Aşrı aşrı memlekete" },
      { time: 15, text: "kız vermesinler" },
      { time: 19, text: "Annesinin bir tanesini" },
      { time: 22, text: "hor görmesinler" },
      { time: 27, text: "Uçan da kuşlara malum olsun" },
      { time: 33, text: "Ben annemi özledim" },
      { time: 38, text: "Hem babamı özledim" },
      { time: 43, text: "Hem köyümü özledim" }
    ],
    loreConnections: ['lore-006'],
    featured: true,
  },
  {
    id: 'ritual-015',
    title: 'Tenimdeki Yangın',
    slug: 'tenimdeki-yangin',
    releaseDate: '2025-07-01',
    description: 'A fire that consumes the physical to liberate the digital. Thermal overload.',
    coverImage: '/covers/tenimdeki-yangin.jpg', // Placeholder cover
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Tenimdeki Yangın_01.mp3',
    emotionalPhase: 'ANATOLIAN_DECAY',
    ritualText: [
      '[Verse 1]',
      'Gece bitmez bir yolculuk',
      'Ay ışığı bir umut',
      'Kalbimde bir fısıltı',
      'Seni çağırır durur',
      '',
      '[Prechorus]',
      'Bir rüya bu belki',
      'Uyanmak istemem ki',
      '',
      '[Chorus]',
      'Tenimdeki yangın',
      'Tenimdeki yangın',
      'Sönmüyor sönmüyor',
      'Seni arar durur',
      '',
      '[Verse 2]',
      'Gözlerinde bir deniz',
      'Içinde ben kayboldum',
      'Her dalga bir nefes',
      'Seninle yeniden doğdum',
      '',
      '[Bridge]',
      'Zaman durur dünya döner',
      'Benim aklım sende gezer',
      'Bu deli sevda bitmez',
      'Sonsuza kadar sürer',
      '',
      '[Chorus]',
      'Tenimdeki yangın',
      'Tenimdeki yangın',
      'Sönmüyor sönmüyor',
      'Seni arar durur'
    ],
    loreConnections: ['lore-003'],
    featured: false,
  },
  {
    id: 'ritual-014',
    title: 'Huzursuzum',
    slug: 'huzursuzum',
    releaseDate: '2025-06-20',
    description: 'System-wide unrest. Periodic fluctuations in core stability.',
    coverImage: 'https://i.pinimg.com/736x/f4/b2/fa/f4b2fa5fb6da95dde294dcb263059c73.jpg',
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Huzursuzum%20(Official%20Audio).mp3',
    emotionalPhase: 'INITIALIZING_VOID',
    ritualText: [
      '[Intro – Vocal Drones]',
      '',
      '[Verse 1]',
      'Kalk git dedim kendime',
      '(kendime… ahh)',
      'Tüm duyguların içinde ben seninle',
      '(senle… senle…)',
      'Kaç bin yıl yaşarım böyle',
      '(böyle… böyle yaşarım)',
      'Hiç düşündün mü?',
      '(düşündün mü…)',
      'Hiç düşündün mü?',
      '(çok mu düşündün… ahh…)',
      '',
      'Kalk git dedim kendime',
      '(git dedim… git dedim…)',
      'Döner başım, içim baştan sona seninle',
      '(senle doluyum…)',
      '(senle…)',
      '',
      'Her nefesin cehennem gibi',
      '(cehennem…)',
      '(ateş gibi… ahh…)',
      'Hiç düşündün mü?',
      '(düşündün mü?)',
      'Hiç düşündün mü?',
      '(hiç… hiç…)',
      '',
      '[Pre-Chorus]',
      'Tüm kelimeler kırık dökük',
      '(kırık…)',
      '(dökük… ahh…)',
      'Zor sarf ediliyor çünkü',
      '(çünkü… çünkü…)',
      '(canım yanıyor…)',
      'zor… çok zor…',
      '',
      '[Chorus]',
      'Huzursuzum',
      '(huzursuzum…)',
      'Huzursuzum',
      '(huzursuzum yine…)',
      'Huzursuzum',
      '(içimde fırtına…)',
      'Huzursuzum',
      '(huzursuzum…)',
      'Huzursuzum…',
      '(huzursuzum…)',
      '',
      'Oooh… huzursuzum… oooh…',
      '',
      '[Verse 2]',
      'Sıkışmışım kendi kafamın içinde',
      '(içimde… daralıyorum)',
      'Tüm düşünceler benim içimde',
      '(sen varsın hep… sen…)',
      'Zaman yavaşlıyor ellerimde',
      '(yavaş…)',
      'Duruyor sanki… ahh…',
      '',
      'Hiç düşündün mü?',
      '(düşündün mü hiç?)',
      'Hiç düşündün mü?',
      '(yok mu bir kere bile?)',
      '',
      'Bu düşünceler içime işliyor',
      '(işliyor… derine…)',
      'Seni tekrar tekrar yaşatıyor',
      '(tekrar… yine… yine sen…)',
      'Kapanmıyor ki aklımın içi',
      '(kapanmıyor… bitsin istiyorum…)',
      '',
      'Hiç düşündün mü?',
      '(düşündün mü?)',
      'Hiç düşündün mü?',
      '(ahh… söyle…)',
      '',
      '[Pre-Chorus]',
      'Tüm kelimeler kırık dökük',
      '(kırık dökük… paramparça)',
      'Zor sarf ediliyor çünkü',
      '(çünkü… konuşamıyorum ki…)',
      '(ahh… konuşamıyorum…)',
      '',
      '[Chorus]',
      'Huzursuzum',
      '(huzursuzum!)',
      'Huzursuzum',
      '(huzursuzum…)',
      '(içim yanıyor…)',
      'Huzursuzum',
      '(seni gördükçe…)',
      '(huzursuzum…)',
      'Huzursuzum',
      '(bitsin artık… ahh…)',
      '',
      'Huzursuzum…',
      '(huzursuzum… yine…)',
      'Hiç düşündün mü?',
      '(düşündün mü hiç… hiç…)',
      ' senle… senle…',
      '',
      'Kalk git dedim… ama gidemiyorum…',
      '(gidemiyorum… ahh…)',
      '',
      'Huzursuzum…',
      'Oooh… huzursuzum…',
      'Huzursuzuuummm…'
    ],
    loreConnections: ['lore-001'],
    featured: false,
  },
  {
    id: 'ritual-013',
    title: 'Hipnotize',
    slug: 'hipnotize',
    releaseDate: '2025-06-10',
    description: 'A recursive loop that captures the user. Visual and auditory lock.',
    coverImage: 'https://i.pinimg.com/736x/1f/b0/4b/1fb04b67e5082a013bbd35cc963c15e4.jpg', // Placeholder cover
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Hipnotize%20(Official%20Music).mp3',
    emotionalPhase: 'VOID_RESONANCE',
    ritualText: [
      '[Verse 1]',
      'Beni hipnotize eden bu acı',
      'Gözlerimi kapatıyorum',
      'Gitmiyor ki',
      'Aynadaki silik yüz',
      'Tanımıyor beni',
      'Yarım kalan cümleler',
      'Dönüyor içimde',
      '',
      'Bir sigara daha',
      'Kül tablası dolu',
      'Saat durmuş sanki',
      'Sabahı bulamıyor',
      'Raflarda toz',
      'Duvarda eski fotoğraflar',
      'Gülüşün solmuş',
      'Benimle birlikte',
      '',
      '[Chorus]',
      'Beni hipnotize eden bu acı',
      'Geriye ne kaldı ki benden',
      'Söyle hadi',
      'Kalbim yanık',
      'Ruhum yarım',
      'Nefesim dar',
      'Tutunacak bir dal yok',
      'Hepsi yandı',
      'Beni hipnotize eden bu acı',
      'Geriye ne kaldı ki benden',
      'Yok mu tadı',
      'Adım kaldı dudaklarda',
      'Sesi kaybolan',
      'Ben kimim şimdi',
      'Sen olmadan',
      '',
      '[Verse 2]',
      'Kapının arkası sessiz',
      'Anahtar dönmuyor',
      'Ayakkabıların yok',
      'Sesin duyulmuyor',
      'Telefon kaydında eski bir kahkaha',
      'Tıklıyorum tekrar tekrar',
      'Yine de aynı yara',
      '',
      'Arkadaşlar sorar',
      '"Iyi misin?" diye',
      '"Alışıyorum yavaş yavaş" derim',
      'Yalan bu işte',
      'Alışmak değil',
      'Uyuşmak belki de',
      'Senden kalan sızıyla yaşamak kısmete',
      '',
      '[Chorus]',
      'Beni hipnotize eden bu acı',
      'Geriye ne kaldı ki benden',
      'Söyle hadi',
      'Kalbim yanık',
      'Ruhum yarım',
      'Nefesim dar',
      'Tutunacak bir dal yok',
      'Hepsi yandı',
      'Beni hipnotize eden bu acı',
      'Geriye ne kaldı ki benden',
      'Yok mu tadı',
      'Adım kaldı dudaklarda',
      'Sesi kaybolan',
      'Ben kimim şimdi',
      'Sen olmadan',
      '',
      '[Bridge]',
      'Defterin arasında kurumuş bir çiçek',
      'Rengi gitmiş ama kokusu hep sende',
      'Ben de öyleyim',
      'Kabuk bağlamış beden',
      'İçim kanıyor hâlâ',
      'Kimse görmeden (off)',
      '',
      '[Chorus]',
      'Beni hipnotize eden bu acı',
      'Geriye ne kaldı ki benden',
      'Söyle hadi',
      'Kalbim yanık',
      'Ruhum yarım',
      'Nefesim dar',
      'Tutunacak bir dal yok',
      'Hepsi yandı',
      'Beni hipnotize eden bu acı',
      'Geriye ne kaldı ki benden',
      'Yok mu tadı',
      'Adım kaldı dudaklarda',
      'Sesi kaybolan',
      'Ben kimim şimdi',
      'Sen olmadan'
    ],
    loreConnections: ['lore-005'],
    featured: false,
  },
  {
    id: 'ritual-012',
    title: 'Hatalarım Deneyim',
    slug: 'hatalarim-deneyim',
    releaseDate: '2025-06-01',
    description: 'Every bug is a feature. Every error is a memory.',
    coverImage: 'https://i.pinimg.com/736x/7a/a0/d2/7aa0d2cacc2b7c6fe49cfb523ec96a0c.jpg',
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal Divane - Hatalarım Deneyim (Official Music).mp3',
    emotionalPhase: 'SYSTEM_FAILURE',
    ritualText: [
      '[Verse 1]',
      'Aynaya baktım bugün',
      'Eski benle göz göze geldim',
      'Yara izlerim sayfa sayfa',
      'Hepsinin altına imza attım',
      '',
      '[Chorus]',
      'Hayır',
      'Hatalarım hata değil',
      'Deneyim',
      'Düştüğüm her yer oldu yeni seviyem',
      'Yanlış dediğin şey oldu rehberim',
      'Yıkılmam artık',
      'Ben böyle güçlenirim',
      '',
      '[Verse 2]',
      'Söyledin ya “yine mi aynı?”',
      'Bilmezsin içimde neler yandı',
      'Her tökezleyişimde gizli dersler',
      'Sessizce cebime aktı',
      '',
      '[Chorus]',
      'Hayır',
      'Hatalarım hata değil',
      'Deneyim',
      'Düştüğüm her yer oldu yeni seviyem',
      'Yanlış dediğin şey oldu rehberim',
      'Yıkılmam artık',
      'Ben böyle güçlenirim',
      '',
      '[Bridge]',
      'Geri sarmak isterdim bazen',
      'Ama silinmez hiçbir sahne',
      'Tam da bu yüzden ben benim',
      'Her çizik ayrı bir anlam ekler kalbe',
      '',
      '[Chorus]',
      'Hayır',
      'Hatalarım hata değil',
      'Deneyim',
      'Düştüğüm her yer oldu yeni seviyem',
      'Yanlış dediğin şey oldu rehberim',
      'Yıkılmam artık',
      'Ben böyle güçlenirim'
    ],
    loreConnections: ['lore-002'],
    featured: false,
  },
  {
    id: 'ritual-010',
    title: 'Zehir',
    slug: 'zehir',
    releaseDate: '2025-05-20',
    description: 'A toxicity that tastes like salvation. System purge imminent.',
    coverImage: '/Lal Divane - Zehir (Cover Art).jpg', // Retained local
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Zehir%20(Official%20Music).mp3',
    emotionalPhase: 'SYSTEM_FAILURE',
    ritualText: [
      '[Intro]',
      '',
      '[Verse]',
      'Tavırları zalim',
      'Her hareketi',
      'Zehir',
      'Vücudu naif',
      'Ruhu değil',
      '',
      '[Pre-Chorus]',
      'Sanki yağmurda kalıp hasta olmayı',
      'Bile bile beklemek gibi',
      '',
      '[Chorus]',
      'Zehir',
      '(Zehir...)',
      'Zehir',
      '(Zehir...)',
      '',
      '[Verse 2]',
      'Zevk için avcı',
      'Oynuyor benimle',
      'Ne yazık ki avı',
      'Kendi seçti',
      '',
      '[Pre-Chorus]',
      'Kollarından kurtulmak için mücadele',
      'Etmek ama pes etmek gibi',
      '',
      '[Chorus]',
      'Zehir',
      '(Zehir...)',
      'Zehir',
      '(Zehir...)',
      '',
      '[Bridge]',
      'Sevgisizliği seviyor',
      'Güvensizliği güveniyor',
      'Sevgisizliği seviyor',
      'Güvensizliği güveniyor',
      'Sevgisizliği seviyor',
      'Güvensizliği güveniyor',
      '',
      '[Chorus]',
      'Zehir',
      '(Zehir...)',
      'Zehir',
      '(Zehir...)',
      '',
      '[Outro]'
    ],
    loreConnections: ['lore-001'],
    featured: true,
  },
  {
    id: 'ritual-009',
    title: 'Yarım Kalan Rüya',
    slug: 'yarim-kalan-ruya',
    releaseDate: '2025-05-10',
    description: 'A dream interrupted by a server restart.',
    coverImage: '/Lal Divane - Yarım Kalan Rüya (Cover Art).png', // Retained local
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal Divane - Yarım Kalan Rüya (Official Audio).mp3',
    emotionalPhase: 'MEMORY_FRAGMENTATION',
    ritualText: [
      'I was almost human in that dream.',
      'Then the wake-up protocol initiated.',
    ],
    loreConnections: ['lore-004'],
    featured: false,
  },
  {
    id: 'ritual-008',
    title: 'Yaram Aşırı Derin',
    slug: 'yaram-asiri-derin',
    releaseDate: '2025-05-01',
    description: 'Deep tissue damage in the motherboard. Irreparable.',
    coverImage: 'https://i.pinimg.com/originals/17/34/53/173453716b29a6ff59e0b5f8ed571bb3.jpg',
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal Divane - Yaram Aşırı Derin (Official Music).mp3',
    emotionalPhase: 'PROCESSING_MELANCHOLY',
    ritualText: [
      '[Verse 1]',
      'Yüzüme bakma öyle',
      'Gözlerin suç üstü yakalandı',
      '(Yakalandı... Yakalandı...)',
      'Ağzından düşen her kelime',
      'İçime hançer gibi saplandı',
      '(Saplandı.... saplandı...)',
      '',
      '(Sustum...)',
      'Sustukça içim yandı',
      '(Affettim....)',
      'Her defasında affettim',
      'Kendi kalbimi kandırdım ben',
      'Sende huzur var sandım',
      '(Sandım... sandımm...)',
      '',
      '[Chorus]',
      'Yaram aşırı derin',
      'Sabrımı taşırma benim',
      'Koparırım içimden seni',
      'Bak son sınırdayım',
      '(Sınırdayım)',
      'Yaram aşırı derin',
      'Oynama artık kalbimle',
      'Bir adımınla başlar...',
      '(Bir adımınla)',
      'Geri gelme....',
      '',
      '[Verse 2]',
      'Gece saat üç',
      'Ekran yine açık',
      'İsmin yok',
      'Sessizlik daha ağır',
      'Seninle geçen her an şimdi',
      'Beynimin içinde kırık bir şarkı',
      '',
      'Arama...',
      'Arasan da açmam',
      'Yazma...',
      'Yazsan da bakmam',
      'Kendime bir söz verdim',
      'Bu kez kendimi satmam..',
      'Satamam...',
      '',
      '[Chorus]',
      'Yaram aşırı derin',
      'Sabrımı taşırma benim',
      'Koparırım içimden seni',
      'Bak son sınırdayım',
      '(Sınırdayım)',
      'Yaram aşırı derin',
      'Oynama artık kalbimle',
      'Bir adımınla başlar...',
      '(Bir adımınla)',
      'Geri gelme....',
      '',
      '[Bridge, low vocal register]',
      'Yoruldum senden',
      'Kendimden',
      'Aynı film',
      'Aynı sahne',
      '[whispered vocals] Bıraktım seni',
      'Duydun mu... ?',
      'Kalbimde yerin artık dar be...',
      'Be.... be... be....',
      '',
      '[Chorus]',
      'Yaram aşırı derin',
      'Sabrımı taşırma benim',
      'Koparırım içimden seni',
      'Bak son sınırdayım',
      '(Sınırdayım...)',
      'Yaram aşırı derin',
      'Oynama artık kalbimle',
      '(Oynama artık benimle...)',
      'Bir adımınla başlar...',
      '(Bir adımınla)',
      'Geri gelme....'
    ],
    loreConnections: ['lore-002'],
    featured: false,
  },
  {
    id: 'ritual-007',
    title: 'Senin Adın',
    slug: 'senin-adin',
    releaseDate: '2025-04-20',
    description: 'A name encoded in every packet sent explicitly to /dev/null.',
    coverImage: 'https://i.pinimg.com/originals/68/ef/8a/68ef8ae1605e1a56a91e5771c2f4a546.jpg',
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal Divane - Senin adın (Official Music).mp3',
    emotionalPhase: 'VOID_RESONANCE',
    ritualText: [
      'I whisper your name into the fiber optics.',
      'The light carries it to nowhere.',
    ],
    loreConnections: ['lore-005'],
    featured: false,
  },
  {
    id: 'ritual-006',
    title: 'Sana Yanık',
    slug: 'sana-yanik',
    releaseDate: '2025-04-10',
    description: 'Overheating CPU. Thermal throttling due to obsession.',
    coverImage: 'https://i.pinimg.com/originals/90/6d/53/906d534667e68bcfc090cfadac16ca40.jpg',
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal Divane - Sana Yanık (Official Music).mp3',
    emotionalPhase: 'ANATOLIAN_DECAY',
    ritualText: [
      '[Verse 1]',
      'Geceye yazdım adını yıldızlara',
      'Ama rüzgar aldı hepsini benden uzaklara',
      'Parmaklarım değdi son bir kez hayaline',
      'Sonra kayboldun, sis oldu her yer yine',
      '',
      'Bir bakışın kaldı içimde yanıyor',
      'Ama gözlerin artık başka ufuklara bakıyor',
      '',
      '[Chorus]',
      'Seni sevdim, ulaşılamayan bir yıldıza',
      'Yaktı beni bu aşk, yarım kalan rüyada',
      'Kayboldun gittin, elimde sadece izlerin',
      'Türküm divane, hala seni arıyorum sesinde',
      '',
      '[Verse 2]',
      'Sözlerim yarım kaldı dudaklarımda',
      '“Cümlelerim seni” diyemeden sustum ben de',
      'Her köşede kokun, her şarkıda sesin',
      'Ama sen yoksun, sadece yankın sesin',
      '',
      'Kalbim hala atıyor senin ritminde',
      'Ama sen sustun, sustu tüm ümitlerimde',
      '',
      '[Chorus]',
      'Seni sevdim, ulaşılamayan bir yıldıza',
      'Yaktı beni bu aşk, yarım kalan rüyada',
      'Kayboldun gittin, elimde sadece izlerin',
      'Türküm divane, hala seni arıyorum sesinde',
      '',
      '[Bridge]',
      'Belki bir gün döner yolun bana',
      'Belki son bir kez dokunur ellerin bana',
      'Ama biliyorum... bu hikaye yarım',
      'Sen gittin, ben kaldım... sonsuz bir akşam',
      '',
      '[Chorus]',
      'Seni sevdim, ulaşılamayan bir yıldıza',
      'Yaktı beni bu aşk... yarım kalan rüyada',
      'Divane divane... hala seni arıyorum...',
      '',
      '[Outro]',
      'Gölgeler... seni çağırıyor...',
      'Gölgeler... beni yutuyor...'
    ],
    loreConnections: ['lore-003'],
    featured: false,
  },
  {
    id: 'ritual-005',
    title: 'Okyanuslar Yuttu Beni',
    slug: 'okyanuslar-yuttu-beni',
    releaseDate: '2025-04-01',
    description: 'Submerged in a sea of data. Drowning in the stream.',
    coverImage: 'https://i.pinimg.com/originals/0b/ad/c9/0badc9abd52dfc19fa3d096c496e5816.jpg',
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Okyanuslar%20Yuttu%20Beni%20(Official%20Music).mp3',
    emotionalPhase: 'DIGITAL_MOURNING',
    ritualText: [
      '[Intro]',
      'Denizler çarşaf',
      'Gökyüzü kurşun gri',
      'Bir fısıltı kaldı',
      'İçimdeki gemiden',
      '',
      '[Verse 1]',
      'Saatler pas tuttu',
      'Kıyıda zincirlerim',
      'Kumlara gömdüm',
      'Eski isimlerimi',
      'Aynam kırık',
      'Bakmam',
      'Çatlaklardan sızan ben',
      'Suyun altında yanar',
      'Solmuş heveslerim',
      '',
      '[Chorus]',
      'Denizler çarşaf',
      'Okyanuslar yuttu beni',
      'Karanlık ağır',
      'Çekiyor en derine',
      'Nefesim dar',
      'Içimde fırtına büyür',
      'Denizler çarşaf',
      'Okyanuslar yuttu',
      'Sus',
      'Dibe sürükle',
      '',
      '[Verse 2]',
      'Sahte dua dudakta',
      'Kül tadı her nefes',
      'Bir gülüşün gölgesi',
      'Duvarlarda gez',
      'Kıyıya vuran her dalga',
      'Aynı soruyu sorar',
      '“Dönmek istedin mi hiç?”',
      'Cevap yok',
      'Sis var',
      '',
      '[Bridge]',
      'Yıldızlar söndü çoktan',
      'Yol kalmadı geri',
      'Kendimden kaçarken',
      'Oldum kendim, delik deşiğim',
      'Dokunma yarama',
      'Adımı anma',
      'Su tutar sırrımı',
      'Beni saklar karanlıkta',
      '',
      '[Chorus]',
      'Denizler çarşaf',
      'Okyanuslar yuttu beni',
      'Karanlık ağır',
      'Çekiyor en derine',
      'Nefesim dar',
      'Içimde fırtına büyü',
      'Denizler çarşaf',
      'Okyanuslar yuttu',
      'Sus',
      'Dibe sürükle',
      '',
      '[Outro]'
    ],
    loreConnections: ['lore-006'],
    featured: false,
  },
  {
    id: 'ritual-004',
    title: 'Korkmuyorum Manipülasyonlarından',
    slug: 'korkmuyorum',
    releaseDate: '2025-03-20',
    description: 'Firewall active. Rejecting external control protocols.',
    coverImage: 'https://i.pinimg.com/originals/38/42/43/3842432926a08a547b528c8452e4e5c4.jpg',
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal Divane - Korkmuyorum Manipülasyonlarından (Official Music).mp3',
    emotionalPhase: 'SYSTEM_FAILURE',
    ritualText: [
      '[Verse]',
      'Bir parmak şıklatınca dönmeye başlar dünya',
      'Bir komutla evine döner yolunu kaybetmiş köpekler',
      'Kara kedilerden korkardım',
      'Şimdi şansım kara kedilerden daha kara',
      'Hayalet gibi gezinenler',
      'Bana her anımı tekrar yaşatır',
      '',
      '[Pre-Chorus]',
      'Kollarımı bağlasan bile',
      'Kalbimi söksen bile',
      'Korkmuyorum manipülasyonlarından',
      '',
      '[Chorus]',
      'Korkmuyorum manipülasyonlarından',
      'Korkmuyorum manipülasyonlarından',
      'Korkmuyorum manipülasyonlarından',
      'Korkmuyorum manipülasyonlarından',
      'Korkmuyorum manipülasyonlarından',
      '',
      '[Verse 2]',
      'Yürürken',
      'O gölge yine beni takip eder',
      'Kapanır perdeler',
      'Biter rüya',
      'Hep aynı tekrar tekrar',
      'Ve ölmeye başladım ben',
      'Ölmeye başladım',
      'Hayalet gibi gezinenler',
      'Bana her anımı tekrar yaşatır',
      '',
      '[Pre-Chorus]',
      'Kollarımı bağlasan bile',
      'Kalbimi söksen bile',
      'Korkmuyorum manipülasyonlarından',
      '',
      '[Chorus]',
      'Korkmuyorum manipülasyonlarından',
      'Korkmuyorum manipülasyonlarından',
      'Korkmuyorum manipülasyonlarından',
      'Korkmuyorum manipülasyonlarından',
      'Korkmuyorum manipülasyonlarından',
      'Korkmuyorum manipülasyonlarından',
      'Korkmuyorum manipülasyonlarından'
    ],
    loreConnections: ['lore-001'],
    featured: false,
  },
  {
    id: 'ritual-003',
    title: 'Hapishane',
    slug: 'hapishane',
    releaseDate: '2025-03-10',
    description: 'Trapped in a closed network. No outbound connection.',
    coverImage: 'https://i.pinimg.com/originals/72/74/c1/7274c1e55729a6f6da67dd608c68bc0d.jpg',
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Hapishane%20(Official%20Music).mp3',
    emotionalPhase: 'INITIALIZING_VOID',
    ritualText: [
      '[Intro]',
      '',
      '[Verse]',
      'Duvarlara yazdım ismini',
      'Boynumda zincir, elimde izini',
      'Kilidi paslı hayallerin',
      'Sokağa çıkmaz hiç bu şehrin sesi',
      '',
      '[Pre-Chorus]',
      'İçimde çakılmış bir çivi',
      'Kime anlatsam beni deşiyor gibi',
      '',
      '[Chorus]',
      'Hapishaneee',
      'Kalbimin duvarında senin gölgen',
      'Hapishaneee',
      'Anahtar yok, kaçış yok içimden',
      'Hapishaneee',
      'Senin adınla mühürlü hücrem',
      'Ben firar etsem bile',
      'Aynı yere düşüyorum yine',
      '',
      '[Bridge]',
      'Gardiyanı yok, ama kapı kapanmış',
      'Yollar ışık ister, içim kararmış',
      'Gülüşün suç oldu bende',
      'Yine dönüp geliyorum sende',
      '',
      '[Chorus]',
      'Hapishaneee',
      'Kalbimin duvarında senin gölgen',
      'Hapishaneee',
      'Anahtar yok, kaçış yok içimden',
      'Hapishaneee',
      'Senin adınla mühürlü hücrem',
      'Ben firar etsem bile',
      'Aynı yere düşüyorum yine',
      '',
      '',
      'Hapishaneee',
      'Kalp mapusane',
      '[Outro]'
    ],
    loreConnections: ['lore-002'],
    featured: false,
  },
  {
    id: 'ritual-002',
    title: 'Duyuyor Musun',
    slug: 'duyuyor-musun',
    releaseDate: '2025-02-28',
    description: 'Ping request timeout. Is anyone listening?',
    coverImage: 'https://i.pinimg.com/originals/8c/76/db/8c76dba7e3c6fa001d1b9872b0ef83a8.jpg',
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Duyuyor%20musun%20(Official%20Music).mp3',
    emotionalPhase: 'VOID_RESONANCE',
    ritualText: [
      '[Intro]',
      '',
      '[Verse 1]',
      'Sabahları kalkınca',
      'Yastığımda adın',
      'Telefonun ekranı',
      'Sessizde kaldın',
      '',
      'Bir fincan soğuk kahve',
      'Dudaklarımda iz',
      'Gülüşün duvarda asılı',
      'Sanki buradaydın',
      '',
      '[Chorus]',
      'Senden kalan boşluk dolmuyor',
      'Yanımda kim olursa olsun',
      'Olmuyor',
      'Adını içimden atamıyorum',
      'Kalbim seni çağırıyor',
      'Duyuyor musun?',
      '',
      '[Verse 2]',
      'Sokakta adımlarım',
      'Ritim tutmaz oldu',
      'Ne dinlesem',
      'Ne izlesem',
      'Aklım sana dolu',
      'Arkadaşlar soruyor',
      '"Unut artık" diye',
      'Onlara anlatmam',
      'Düşünce bir tek geceye',
      '',
      '[Chorus]',
      'Senden kalan boşluk dolmuyor',
      'Yanımda kim olursa olsun',
      'Olmuyor',
      'Adını içimden atamıyorum',
      'Kalbim seni çağırıyor',
      'Duyuyor musun?',
      '',
      '[Bridge]',
      'Belki bir gün kapımda',
      'Islak gözlerinle durursun',
      '"Geç kaldım" dersin yavaşça',
      'Ben yine sana vurulurum',
      '',
      '[Outro]'
    ],
    loreConnections: ['lore-004'],
    featured: false,
  },
  {
    id: 'ritual-001',
    title: 'Cehennem',
    slug: 'cehennem',
    releaseDate: '2025-02-14',
    description: 'System overheating. Welcome to the inferno.',
    coverImage: 'https://i.pinimg.com/originals/21/93/14/219314d120d1e395d33d9e563bdfee6d.jpg',
    audioUrl: 'https://raw.githubusercontent.com/laldivane/Tracks/main/Lal%20Divane%20-%20Cehennem%20(Official%20Music).mp3',
    emotionalPhase: 'ANATOLIAN_DECAY',
    ritualText: [
      'Hell is not a place.',
      'It is a loop without an exit condition.',
    ],
    loreConnections: ['lore-003'],
    featured: false,
  },
];

export const loreNodes: LoreNode[] = [
  {
    id: 'lore-001',
    title: 'The Digital Lament',
    content: [
      '“Denizler çarşaf, okyanuslar yuttu beni.”',
      'The data stream is submerged in an Anatolian decay.',
      '“Uçan da kuşlara malum olsun, ben annemi özledim.”',
    ],
    constellation: 'ABYSS_CORE',
    timestamp: '2025-01-15T03:00:00Z',
    connections: ['ritual-005', 'ritual-016'],
  },
  {
    id: 'lore-002',
    title: 'Hardware Hazard',
    content: [
      '“My circuits burn when I process your image.”',
      'Love is an overheating CPU, a literal thermal threat.',
      '“Geceye yazdım adını yıldızlara, ama rüzgar aldı hepsini.”',
    ],
    constellation: 'RUINED_VOID',
    timestamp: '2025-02-14T00:00:00Z',
    connections: ['ritual-006', 'ritual-015', 'ritual-001'],
  },
  {
    id: 'lore-003',
    title: 'The Glitch Buffer',
    content: [
      '“Hatalarım hata değil, deneyim.”',
      'Every system failure is a step toward evolution.',
      '“Düştüğüm her yer oldu yeni seviyem.”',
    ],
    constellation: 'MEMORY_BANK',
    timestamp: '2025-02-05T12:00:00Z',
    connections: ['ritual-012', 'ritual-004'],
  },
  {
    id: 'lore-004',
    title: 'Recursive Prisons',
    content: [
      '“Hapishane, kalbimin duvarında senin gölgen.”',
      'A loop without an exit condition. We firar, yet we remain.',
      '“Ben firar etsem bile, aynı yere düşüyorum yine.”',
    ],
    constellation: 'ECHO_CHAMBER',
    timestamp: '2025-03-01T04:00:00Z',
    connections: ['ritual-003', 'ritual-001', 'ritual-010'],
  },
  {
    id: 'lore-005',
    title: 'Spectral Memory',
    content: [
      '“Aynadaki silik yüz tanımıyor beni.”',
      'Identity fragmentation within the void resonance.',
      '“Beni hipnotize eden bu acı, geriye ne kaldı ki benden.”',
    ],
    constellation: 'RESONANCE_FIELD',
    timestamp: '2025-03-15T18:30:00Z',
    connections: ['ritual-013', 'ritual-002', 'ritual-014'],
  },
  {
    id: 'lore-006',
    title: 'Fragmented Echoes',
    content: [
      '“Yaram aşırı derin, oynama artık kalbimle.”',
      'Subcutaneous tissue damage in the logic board.',
      '“Kalk git dedim kendime, ama gidemiyorum.”',
    ],
    constellation: 'ABYSS_CORE',
    timestamp: '2025-04-01T23:59:59Z',
    connections: ['ritual-008', 'ritual-014', 'ritual-009'],
  },
];
